### ISSUE TITLE
Generating super vector

### ISSUE THREAD

**Issue by Rasipuram** [kleinzcy/speech_signal_processing#1]
Hi,

Thank you for providing a nice repository. I have a question regarding training a gmm-ubm model.

I have generated MFCC vectors for my data (binary classification task. Data is in the form of (#utternaces)*(#frames/utterance)*39 for both classes). I want to use GMM-UBM model to train on the MFCC features and build a super vector of dimension 39*No.of Mixtures. How can I use your code to 1) train model and 2) compute SV.

**Comment by kleinzcy** [comment]
Sorry, I didn't reply in time.

My code is just a reference,  and you can not directly use my code in your task. And I don't kown how to generate a super vector from GMM-UBM model. 

Maybe,  you can refer [GMM](https://scikit-learn.org/stable/modules/generated/sklearn.mixture.GaussianMixture.html#sklearn.mixture.GaussianMixture)  to train you model(UBM model just train on whole data). But, I don't know how to generate a super vector from model.  The params of GMM-UBM model?

**Comment by Rasipuram** [comment]
Thank you for your response. I will use GMM on whole data.
