### ISSUE TITLE
The download href does not exist.

### ISSUE THREAD

**Issue by jeremy110** [kleinzcy/speech_signal_processing#2]
Hi bro.I'm interesting in your project and it is great.But the href does not exist.
Can you reupload the href,please?

**Comment by kleinzcy** [comment]
@jeremy110 Can you point out which href does not exist?

**Comment by jeremy110** [comment]
Thanks for your reply.I click the here and return the page.I'm not sure whether it is my problem.

![1594999669741](https://user-images.githubusercontent.com/52516810/87803634-5924a200-c885-11ea-92a6-9b7b32841ec0.jpg)
![1594999704930](https://user-images.githubusercontent.com/52516810/87803654-62157380-c885-11ea-8a26-bbc2bed24918.jpg)

**Comment by jeremy110** [comment]
In addition,I want to use your code to train the d-vector and connect with https://github.com/google/uis-rnn.

**Comment by kleinzcy** [comment]
> Thanks for your reply.I click the here and return the page.I'm not sure whether it is my problem.
> 
> ![1594999669741](https://user-images.githubusercontent.com/52516810/87803634-5924a200-c885-11ea-92a6-9b7b32841ec0.jpg)
> ![1594999704930](https://user-images.githubusercontent.com/52516810/87803654-62157380-c885-11ea-8a26-bbc2bed24918.jpg)

I have test the herf, and it is ok for me.
![image](https://user-images.githubusercontent.com/35723500/87847945-7e112780-c90e-11ea-954b-47b6e3501e98.png)

The herf is https://pan.baidu.com/s/1P65s2OAqqsnnfFOn6XCbSA. If you failed again, you can generate feature by yourself. It is a good chance to exercise.

**Comment by kleinzcy** [comment]
> In addition,I want to use your code to train the d-vector and connect with https://github.com/google/uis-rnn.

Good idea. you can try it! 

Good luck!

**Comment by jeremy110** [comment]
OK,thanks.I will try it!!
